// SEO 学习中心 · 课程数据
// 视频托管在 Google Drive，嵌入地址格式：https://drive.google.com/file/d/<id>/preview
// 待办：把每个视频上传到 Drive 后，把 FILE_ID 填进对应的 id 字段
//   type: "video" 视频 / "doc" PDF·Word / "text" 图文（后两者也用 Drive 托管原文件）
//   platform: build 建站 / keyword 关键词调研 / content 内容与页面优化 / tools 站长工具与进阶
const VIDEOS = [
  { n: "01", platform: "build", group: "SEO 导学篇", id: "", title: "导学部分" },
  { n: "02", platform: "build", group: "WordPress 建站教程", id: "", title: "新手使用wordpress 10大坑" },
  { n: "03", platform: "build", group: "WordPress 建站教程", id: "", title: "网站空间的选择" },
  { n: "04", platform: "build", group: "WordPress 建站教程", id: "", title: "Wordpress后台基础知识" },
  { n: "05", platform: "build", group: "WordPress 建站教程", id: "", title: "B端产品的3种管理方式" },
  { n: "06", platform: "build", group: "WordPress 建站教程", id: "", title: "SMTP的设置" },
  { n: "07", platform: "build", group: "WordPress 建站教程", id: "", title: "认识Elementor" },
  { n: "08", platform: "build", group: "WordPress 建站教程", id: "", title: "使用Elementor制作页面" },
  { n: "09", platform: "build", group: "WordPress 建站教程", id: "", title: "模板下载与上传" },
  { n: "10", platform: "build", group: "WordPress 建站教程", id: "", title: "模板的配置" },
  { n: "11", platform: "build", group: "WordPress 建站教程", id: "", title: "模板修改方法" },
  { n: "12", platform: "build", group: "WordPress 建站教程", id: "", title: "共用模板制作" },
  { n: "13", platform: "build", group: "WordPress 建站教程", id: "", title: "询盘弹窗表单" },
  { n: "14", platform: "build", group: "WordPress 建站教程", id: "", title: "产品描述在模板中调用出来" },
  { n: "15", platform: "build", group: "WordPress 建站教程", id: "", title: "导航固定在顶部" },
  { n: "16", platform: "build", group: "WordPress 建站教程", id: "", title: "C端独立站建站教程" },
  { n: "17", platform: "build", group: "AI 建站与 Astro 架构", id: "", title: "AI工具的选择和API配置" },
  { n: "18", platform: "build", group: "AI 建站与 Astro 架构", id: "", title: "从虚拟主机安装Wordpress程序" },
  { n: "19", platform: "build", group: "AI 建站与 Astro 架构", id: "", title: "必须安装Yoast插件和一个Wordpress主题" },
  { n: "20", platform: "build", group: "AI 建站与 Astro 架构", id: "", title: "Wordpress对接后台并创建页面、修改页面、配图" },
  { n: "21", platform: "build", group: "AI 建站与 Astro 架构", type: "text", id: "", url: "https://seogeo.cc/ai-agent-b2b", title: "免费服务器Cloudflare 上 AI 搭建B2B网站" },
  { n: "22", platform: "keyword", group: "解密 Semrush", id: "", title: "使用Semrush分析一个网站" },
  { n: "23", platform: "keyword", group: "解密 Semrush", id: "", title: "Semrush分析网站外链" },
  { n: "24", platform: "keyword", group: "解密 Semrush", id: "", title: "Semrush调研关键词" },
  { n: "25", platform: "keyword", group: "解密 Semrush", id: "", title: "使用Semrush和竞争对手PK" },
  { n: "26", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "关键词调研目的：找用户需求" },
  { n: "27", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "关键词调研1：以词找词" },
  { n: "28", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "关键词调研2：用站找词" },
  { n: "29", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "关键词调研3：筛选利基（挑选关键词）" },
  { n: "30", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "关键词调研4：关键词布局" },
  { n: "31", platform: "keyword", group: "捕鱼模式关键词调研", id: "", title: "俄罗斯Yandex关键词调研，谷歌以外的市场调研方法" },
  { n: "32", platform: "content", group: "页面优化 Title 和 Meta", id: "", title: "页面优化 标题 title和元描述" },
  { n: "33", platform: "content", group: "AI 写内容及内容优化", type: "doc", id: "", title: "AI工具如何写好SEO文章" },
  { n: "34", platform: "content", group: "AI 写内容及内容优化", id: "", title: "AI写内容（找话题、整理大纲、AI工具使用）" },
  { n: "35", platform: "content", group: "AI 写内容及内容优化", id: "", title: "如何优化AI生成的文章" },
  { n: "36", platform: "content", group: "图片 SEO", id: "", title: "图片大小优化" },
  { n: "37", platform: "content", group: "图片 SEO", id: "", title: "图片ALT标签优化" },
  { n: "38", platform: "tools", group: "谷歌站长 GSC / Bing / StatCounter", id: "", title: "如何开通GSC" },
  { n: "39", platform: "tools", group: "谷歌站长 GSC / Bing / StatCounter", id: "", title: "GSC后台功能介绍" },
  { n: "40", platform: "tools", group: "谷歌站长 GSC / Bing / StatCounter", id: "", title: "Bing站长工具的开通和Clarity热力图功能的开通" },
  { n: "41", platform: "tools", group: "谷歌站长 GSC / Bing / StatCounter", id: "", title: "StatCounter用户跟踪" },
  { n: "42", platform: "tools", group: "Yoast SEO 插件设置", id: "", title: "Yoast SEO插件的设置" },
  { n: "43", platform: "tools", group: "Yoast SEO 插件设置", type: "doc", id: "", title: "robots.txt参考案例" },
  { n: "44", platform: "tools", group: "支柱页面与主题集群", id: "", title: "支柱 + 主题集群创建" },
];
